<?php

function ww_bootstrap4_layouts_preprocess_layout__bs_donation_slider(&$variables) {
    if ($variables['content']['#entity'] instanceof \Drupal\block_content\Entity\BlockContent) {
      $block = $variables['content']['#entity'];
  
      if (!$block->get('field_donation_slider_items')->isEmpty()) {
        $carousel_items = $block->get('field_donation_slider_items')->referencedEntities();
        foreach($carousel_items as $item) {
          $view_builder = \Drupal::entityTypeManager()->getViewBuilder($item->getEntityTypeId());
          $variables['items'][] = $view_builder->view($item);;
        }
      }
  
      $variables['donation_slider_id'] = $block->id();
    }
  }